### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lstables** [mjanssen/Laravel-4-breadcrumb#1]
Getting this error when using:

{{ Breadcrumb::generate() }} in my view

Undefined property: Mj\Breadcrumb\Breadcrumb::$breadcrumbs

**Comment by mjanssen** [comment]
Hey there :).

How did you implement the breadcrumb provider? Did you register them in your app.php?
Also, did you set some breadcrumbs first?

**Comment by lstables** [comment]
No i just set {{ Breadcrumb::generate() }} in my view

**Comment by mjanssen** [comment]
Here, I've made some code to help you further. I hope this will work for you :)

http://paste.laravel.com/1few

**Comment by lstables** [comment]
Yes i just added some of that in and worked a treat, just out of interest for newbies like me I would alter your readme to say they need to enter the addBreadcrumb in controllers etc so they fully understand

**Comment by mjanssen** [comment]
Will do !! :)

Glad I could help out!

**Comment by lstables** [comment]
Thanks, nice library too, works a breeze!

**Comment by lstables** [comment]
Also another suggestion would be to make a config file for it so people can set their own seperators etc

**Comment by mjanssen** [comment]
The breadcrumb.php can be edited without problems. There you can also see that there's a function "setSeperator" which you can use :). Breadcrumb::setSeperator('/'); will edit the seperator for the current breadcrumbs.

**Comment by lstables** [comment]
Yes i realize that, but was just a thought :)
