### ISSUE TITLE
Unnessary escaped double quotes

### ISSUE THREAD

**Issue by opheliadesign** [mjanssen/Laravel-4-breadcrumb#3]
Line 37 in the `generate` method - 
`$output .= '<div class=\"clearfix\"></div>';`

The escaped double quotes are not necessary and appear in HTML.
Also, Bootstrap 3 breadcrumbs append a divider automatically - having to constantly override this. A publishable Config file would be very helpful.

Thanks for making this!

**Comment by mjanssen** [comment]
Hey there!

The double quotes are removed (no clue why they were there anyways...). With the config file (src/config/config.php) you can now enable or disable the separator.

Thanks for the tips (:

If you have more suggestions, let 'em know and I'll see what I can do!

**Comment by opheliadesign** [comment]
Thanks! Will check it out. And thanks again for making this. 

On June 27, 2014 3:16:38 AM EDT, Marnix Janssen notifications@github.com wrote:

> Hey there!
> 
> The double quotes are removed (no clue why they were there anyways...).
> With the config file (src/config/config.php) you can now enable or
> disable the separator.
> 
> Thanks for the tips (:
> 
> If you have more suggestions, let 'em know and I'll see what I can do!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mjanssen/Laravel-4-breadcrumb/issues/3#issuecomment-47314499

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
