### ISSUE TITLE
Undefined index: enable_seperator

### ISSUE THREAD

**Issue by quog** [mjanssen/Laravel-4-breadcrumb#4]
After a composer update I am getting

ErrorException (E_UNKNOWN) 
Undefined index: enable_seperator

public function __construct()
    {
        $this->config = Config::get('Breadcrumb::config');

```
    $this->seperator = ($this->config['enable_seperator'] === true)
                        ? '<span class="divider">'.$this->config['default_seperator'].'</span>'
                        : '';
```

It seems it's not finding your new config file - is there a step missing to add this to the Config system?

Also - note spelling of separator.

**Comment by ledmirage** [comment]
I had the same issue, try changing vendor/mj/breadcrumb/src/Config to config (small c). you are probably using linux (or similar) OS which is case sensitive for folder name

**Comment by quog** [comment]
That works.  I also had to change vendor/mj/breadcrumb/src/Mj/Breadcrumb/breadcrumb.php to vendor/mj/breadcrumb/src/Mj/Breadcrumb/Breadcrumb.php (had to on previous version too.)

**Comment by mjanssen** [comment]
Hi guys,

I'm currently working on the case sensitive problems and the spelling errors (excuses for that ...).

Git does not care about me editing the capital letters on folders & files, so I have to find a workaround for that.

**Comment by ledmirage** [comment]
maybe u can check your git setting? sounds like git is ignoring case on your project, or try this?
$ git config core.ignorecase false

**Comment by mjanssen** [comment]
Fixed everything and updated package. Composer update should fix the errors. Please notify me if there are still errors :)

**Comment by quog** [comment]
Works fine once I changed calls to setSeperator() to setSeparator().

**Comment by quog** [comment]
p.s. thanks for the great package.

**Comment by mjanssen** [comment]
Thanks! I've also edited the readme typo's.

Thank you for noticing and notifying :)
